ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;
ALTER TABLE Mark ALTER COLUMN mark INT NOT NULL CHECK (mark >= 1 AND mark <= 10), ALTER COLUMN student_id BIGINT NOT NULL, ALTER COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE Subject ALTER COLUMN groupnumber INT NOT NULL CHECK (groupnumber >= 1 AND groupnumber <= 5);
ALTER TABLE PaymentType ADD CONSTRAINT unique_name UNIQUE (name);
ALTER TABLE Payment ALTER COLUMN type_id BIGINT NOT NULL, ALTER COLUMN amount DECIMAL(10,2) NOT NULL, ALTER COLUMN payment_date TIMESTAMP NOT NULL;