ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;
ALTER TABLE Mark ALTER COLUMN mark INT NOT NULL ADD CONSTRAINT changeMarkRange CHECK(mark between 1 and 10);
ALTER TABLE Mark ALTER COLUMN student_id BIGINT NOT NULL;
ALTER TABLE Mark ALTER COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE Subject ALTER groupnumber INT NOT NULL ADD CONSTRAINT changeSubjectCourseRange CHECK(groupnumber between 1 and 5);
ALTER TABLE PaymentType ADD CONSTRAINT unique_name UNIQUE (name);
ALTER TABLE Payment ALTER type_id BIGINT NOT NULL;
ALTER TABLE Payment ALTER amount DECIMAL(10,2) NOT NULL;
ALTER TABLE Payment ALTER payment_date TIMESTAMP NOT NULL;
